# Generated by Django 3.1.1 on 2020-09-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='parents',
            new_name='parent',
        ),
    ]
